### ISSUE TITLE
Notary documentation

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#10]
While the defaultnotary.php file is very short and easy to follow due to good function and parameter naming, it exposes two public functions which should be documented so that automatically generated documentation is complete.

**Comment by monsterbitar** [comment]
Ah, I see that the notary interface is documented elsewhere. I'm unfamiliar with how to best handle this.

**Comment by monsterbitar** [comment]
On a related note: the request cache interface and implementation both lack this documentation.

**Comment by Beakerboy** [comment]
Doxygen will, by default, push the parent documentation to a child function unless overridden. Since the interface is fully documented, the autodocumentation will use it for and class that implements the interface. You can look at the documentation that is linked on the main README.md to see how it currently looks.

**Comment by monsterbitar** [comment]
I've looked at the generated documentation and the notary interface is documented properly there. The request generator interface however has minimal information:

https://codedocs.xyz/Beakerboy/CashID/interfaceCashID_1_1Cache_1_1RequestCacheInterface.html

Generally I prefer to browser the code, and find it odd that the documentation is missing in some places, but since this is just my personal behaviour pattern I'd say that part is fine as it is.

Once the request generator is documented in the same way as the notary, that should be all that is needed to close this issue.

**Comment by Beakerboy** [comment]
It looks like doxygen supports @inheritdoc. By adding the docblock:
````php
/**
 * @inheritdoc
 */
````
above a function, it will allow the documentation engine to use the parent documentation for the children classes, while also giving cues to someone reading the code where to find the documentation.

**Comment by Beakerboy** [comment]
Also, instead of using Doxygen with codedocz.xyz, I could generate static pages on travis and push them the github-pages space using PHPDoc. Doxygen works with any language, but the draft PSR-19 describes a PHP specific documentation standard.

**Comment by monsterbitar** [comment]
inheritdoc sounds like a good way to make it clear in the code that documentation is provided elsewhere.

for the change in documentation engine or any other drastic changes I don't think they are needed, but feel free to do what you think is best there.

Soon we should have no real issues left to deal with and I'd like to merge upstream.
