### ISSUE TITLE
File structure: grouping

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#11]
When looking over the source code I jumped back and forth a bit as needed. One thing I feel would be good is to have the notary and cache related files in their own subfolders as they logically belong together but their naming does not start with their most significant (and most importantly: common) wording.

Essentially just move the two (interface, default implementation) files into a folder named after their function.

**Comment by Beakerboy** [comment]
Should I move the cache files to the namespace `\CashID\Cache\` and the notary files to `\CashID\Notary\` while using corresponding directory structure as well?

**Comment by Beakerboy** [comment]
Fixed

**Comment by monsterbitar** [comment]
For reference, yes, I think it was good to make that further distinction.
