### ISSUE TITLE
Misplaced documentation

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#12]
In the response handler code, this comment is at the top of the file:

/**
 * Simple CashID support library that can:
 * - Verify requests
 * - Send status confirmations
 *
 * Requirements for this library to function:
 * - PHP support for PECL APCu
 */

This should problably be moved elsewhere, removed or rewritten to better match the new structure.

**Comment by Beakerboy** [comment]
You’re right. I need class specific doc-blocs that specify what role each class fulfills within the project.

**Comment by Beakerboy** [comment]
Fixed
