### ISSUE TITLE
Update comments

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#13]
Here it states that we use bitcoind, but that has been factored out:

https://github.com/Beakerboy/CashID/blob/d4b3c7bf91f5023409d37307dd004dc1eae8d1f6/src/ResponseHandler.php#L201

**Comment by monsterbitar** [comment]
Here it reference cashid->confirm_request:

https://github.com/Beakerboy/CashID/blob/d4b3c7bf91f5023409d37307dd004dc1eae8d1f6/src/ResponseHandler.php#L276

(wrong camelcase, old style reference, should problably be written differently.)

**Comment by monsterbitar** [comment]
Here it also references old code format/style/structure:

https://github.com/Beakerboy/CashID/blob/d4b3c7bf91f5023409d37307dd004dc1eae8d1f6/src/ResponseHandler.php#L281

**Comment by Beakerboy** [comment]
Fixed
