### ISSUE TITLE
Coding Standard, PSR2 or PSR4?

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#4]
In the coding standards file, it lists PSR2, but I was under the impression this would be PSR4.

I don't know what either are, just making a note that they are different in case it matters.

**Comment by Beakerboy** [comment]
PSR-2 deals with whitespace, parameter and function naming, and control structure formats.

PSR-4 deals with namespacing, autoloading, and class file names.

**Comment by monsterbitar** [comment]
I see, and PSR4 does not imply PSR2 then? If so, it's all good and this can be closed.

**Comment by Beakerboy** [comment]
I added a PSR-4 sniff to the coding standard just to ensure that name-spacing and file naming continues to match that standard.
#14
