### ISSUE TITLE
String or NULL?

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#6]
When generating a new request, I used to pass NULL when I did not have any action or data, but there is now type-enforcement.

I can pass empty strings instead, but if it's possible to enforce "NULL or NON-EMPTY STRING" then that'd be my preference.

I'm fine either way, and have already converted to empty strings.

**Comment by Beakerboy** [comment]
PHP 7.1 introduced nullable types. You can type hint `?string` to indicate string or null. If tou’re ok with making 7.0 unsupported, I can do that.

**Comment by monsterbitar** [comment]
I am ok with not supporting 7.0, please go ahead and update this.

**Comment by Beakerboy** [comment]
Fixed
