### ISSUE TITLE
User Initiated Actions: Don't suggest nonces

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#7]
On this line:

https://github.com/Beakerboy/CashID/blob/d4b3c7bf91f5023409d37307dd004dc1eae8d1f6/src/RequestGenerator.php#L69

There should probably be a check for the nature of the action, and for user-initiated actions the nonce should be omitted. (randomyl generated nonces rarely end up as good valid timestamps)

**Comment by Beakerboy** [comment]
If an action is user-initiated, should the RequestGenerator even be allowed to create a request?

**Comment by monsterbitar** [comment]
Good question. The only legitimate reason to generate a request that is normally intended to be user-initiated, is so you can easily create a QR code (or otherwise) to help the user more easily find and trigger the functionality.

I think for this reason it should be allowed to do so, but omit the nonce. Perhaps it makes sense to not store it as a a request as well, since the user is supposed to put a valid timestamp as the nonce making it no longer match the request identifier.

If you have any other ideas, I'm open to listening to feedback and willing to change my mind on this.

**Comment by Beakerboy** [comment]
That’s in line with what I was thinking.

**Comment by Beakerboy** [comment]
Fixed
