### ISSUE TITLE
Test case documentation

### ISSUE THREAD

**Issue by monsterbitar** [Beakerboy/CashID#9]
While not strictly a problem, when readin the test case code I found myself puzzled and re-reading the code trying to figure out what the intent is behind it.

I understand that someone who is used to making and using test frameworks should immidiately recognize what is going on, but if possible I would appreciate that all code is statement-by-statement documented.

Even if only because it helps me understand what the hell I was thinking when I've learned more and re-read old code 5~15 years laters.

**Comment by Beakerboy** [comment]
No problem. Let me know if there are any particularly confusing sections of code.

**Comment by Beakerboy** [comment]
I've reorganized some of the tests and added more comments. Again, let me know if you find anything confusing. Some is likely "learning how PHPUnit works" on your side and some is stuff to explain why it's doing what it's doing.
